# Created by: Gvozdikov Veniamin <g.veniamin@googlemail.com>
# $FreeBSD$

PORTNAME=	couchbase
PORTVERSION=	1.8.1
CATEGORIES=	databases
MASTER_SITES=	http://packages.couchbase.com/releases/${PORTVERSION}/
DISTNAME=	${PORTNAME}-server_src-${PORTVERSION}

MAINTAINER=	g.veniamin@googlemail.com
COMMENT=	Couchbase Server is a simple, fast, elastic, open-source NoSQL database.

USE_GMAKE=	yes

WRKSRC=		${WRKDIR}/${PORTNAME}-server_src

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
