# New ports collection makefile for:	stardict-engcom
# Date created:		2010-03-16
# Whom:			Gvozdikov Veniamin <g.veniamin@googlemail.com>
#
# $FreeBSD: ports/russian/stardict-engcom/Makefile,v 1.1 2010/03/24 19:35:22 makc Exp $
#

PORTNAME=	stardict-engcom
PORTVERSION=	2.4.2
CATEGORIES=	russian
MASTER_SITES=	SF/stardict/stardict-dictionaries-ru/${PORTVERSION}
DISTNAME=	${PORTNAME}-ru-${PORTVERSION}

MAINTAINER=	g.veniamin@googlemail.com
COMMENT=	English-Russian Dictionary of Computer Terms

.include "${.CURDIR}/../stardict-mueller7/files/Makefile.common"
.include <bsd.port.mk>
