# New ports collection makefile for:	linux-f10-gconf2
# Date created:		2009-11-10
# Whom:			Gvozdikov Veniamin <g.veniamin@googlemail.com>
#
# $FreeBSD$
#

PORTNAME=	gconf2
PORTVERSION=	2.24.0
CATEGORIES=	devel linux
PKGNAMEPREFIX=	linux-f10-
DISTNAME=	GConf2-${PORTVERSION}-${RPMVERSION}

MAINTAINER=	g.veniamin@googlemail.com
COMMENT=	A configuration database system for GNOME

ONLY_FOR_ARCHS=	i386 amd64
USE_LINUX_RPM=	yes
LINUX_DIST_VER= 10
RPMVERSION=	1.fc10
USE_LDCONFIG=	yes

#DESCR=		${.CURDIR}/../${PORTNAME}/pkg-descr

.include <bsd.port.mk>
