# New ports collection makefile for:	gizmo5
# Date created:		2009-11-11
# Whom:			Gvozdikov Veniamin <g.veniamin@googlemail.com>
#
# $FreeBSD$
#

PORTNAME=	gizmo5
PORTVERSION=	3.1.0.79
CATEGORIES=	net
MASTER_SITES=	http://download.gizmo5.com/GizmoDownload/
DISTNAME=	gizmo-project-${PORTVERSION}-1-libstdc++6

MAINTAINER=	g.veniamin@googlemail.com
COMMENT=	P2P VoIP software

USE_LINUX=	yes
USE_LINUX_APPS=	alsalib	gtk2

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
