# New ports collection makefile for:	linux-f10-v8
# Date created:		2009-11-10
# Whom:			Gvozdikov Veniamin <g.veniamin@googlemail.com>
#
# $FreeBSD$
#

PORTNAME=	v8
PORTVERSION=	1.3.16
CATEGORIES=	linux
MASTER_SITES=	http://spot.fedorapeople.org/chromium/F10/
PKGNAMEPREFIX=	linux-f10-
DISTNAME=	${PORTNAME}-${PORTVERSION}-${RPMVERSION}

MAINTAINER=	g.veniamin@googlemail.com
COMMENT=	V8 JavaScript Engine

USE_LINUX_RPM=	yes
USE_LINUX=	yes
ONLY_FOR_ARCH=	i386 amd64
LINUX_DIST_VER=	10
USE_LDCONFIG=	yes
RPMVERSION=	1.20091027svn3152.fc10

.include <bsd.port.mk>
