# New ports collection makefile for:	feelhome
# Date created:		2010-03-23
# Whom:			Gvozdikov Veniamin <g.veniamin@googlemail.com>
#
# $FreeBSD$
#

PORTNAME=	feelhome
PORTVERSION=	0.3.0.504
CATEGORIES=	net
MASTER_SITES=	SF/${PORTNAME}/FeelHome-${PORTVERSION}
DISTNAME=	FeelHome-${PORTVERSION}

MAINTAINER=	g.veniamin@googlemail.com
COMMENT=	

.include <bsd.port.mk>
