# New ports collection makefile for:	libplist
# Date created:		2010-09-22
# Whom:			Gvozdikov Veniamin <g.veniamin@googlemail.com>
#
# $FreeBSD$
#

PORTNAME=	libplist
PORTVERSION=	1.3
CATEGORIES=	audio
MASTER_SITES=	http://cloud.github.com/downloads/JonathanBeck/${PORTNAME}/

MAINTAINER=	g.veniamin@googlemail.com
COMMENT=	Apple Binary and XML Property Lists

USE_BZIP2=	yes
USE_CMAKE=	yes
USE_GNOME=	glib20 libxml2

LICENSE=	GPLv2

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
