# New ports collection makefile for:	openerp-client
# Date created:		2009-11-12
# Whom:			Gvozdikov Veniamin <g.veniamin@googlemail.com>
#
# $FreeBSD$
#

PORTNAME=	openerp-client
PORTVERSION=	5.0.6
CATEGORIES=	finance python
MASTER_SITES=	http://openerp.com/download/stable/source/
DISTNAME=	${PORTNAME}-${PORTVERSION}

MAINTAINER=	g.veniamin@googlemail.com
COMMENT=	Open source application ERP & CRM

USE_PYTHON=	yes

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
