# New ports collection makefile for:	vlogger
# Date created:		2010-07-21
# Whom:			Gvozdikov Veniamin <g.veniamin@googlemail.com>
#
# $FreeBSD$
#

PORTNAME=	vlogger
PORTVERSION=	1.3
CATEGORIES=	sysutils
MASTER_SITES=	http://n0rp.chemlab.org/${PORTNAME}/

MAINTAINER=	g.veniamin@googlemail.com
COMMENT=	

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
