# New ports collection makefile for:	php5-blitz
# Date created:		2011-04-25
# Whom:			Gvozdikov Veniamin <g.veniamin@googlemail.com>
#
# $FreeBSD$
#

PORTNAME=	blitz
PORTVERSION=	0.7.1.10
CATEGORIES=	www
MASTER_SITES=	http://alexeyrybak.com/blitz/
PKGNAMEPREFIX=	php5-
DISTNAME=	${PORTNAME}-${PORTVERSION}-devel

MAINTAINER=	g.veniamin@googlemail.com
COMMENT=	Blitz templates, template engine extension for PHP

USE_PHP=	yes
USE_PHPIZE=	yes
USE_PHPEXT=	yes
PHP_MODNAME=	${PORTNAME}

WRKSRC=		${WRKDIR}/${PORTNAME}-${PORTVERSION}-devel

.include <bsd.port.mk>
