# New ports collection makefile for:	grub2
# Date created:		2009-10-29
# Whom:			Gvozdikov Veniamin <g.veniamin@googlemail.com>
#
# $FreeBSD$
#

PORTNAME=	grub2
PORTVERSION=	1.97
CATEGORIES=	sysutils
MASTER_SITES=	ftp://alpha.gnu.org/gnu/grub/
DISTNAME=	grub-${PORTVERSION}

MAINTAINER=	g.veniamin@googlemail.com
COMMENT=	GRand Unified Bootloader

USE_AUTOTOOLS=  autoconf:262
GNU_CONFIGURE=	yes
USE_GMAKE=	yes

USE_RUBBY=	16

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
