# Created by: Gvozdikov Veniamin <g.veniamin@googlemail.com>
# $FreeBSD: ports/devel/cityhash/Makefile,v 1.1 2013/02/10 21:28:18 svnexp Exp $

PORTNAME=	cityhash
PORTVERSION=	1.1.0
CATEGORIES=	devel
MASTER_SITES=	GOOGLE_CODE

MAINTAINER=	g.veniamin@googlemail.com
COMMENT=	Family of hash functions

LICENSE=	MIT

GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes

.include <bsd.port.mk>
