# New ports collection makefile for:	libimobiledevice
# Date created:		2010-09-22
# Whom:			Gvozdikov Veniamin <g.veniamin@googlemail.com>
#
# $FreeBSD$
#

PORTNAME=	libimobiledevice
PORTVERSION=	1.0.2
CATEGORIES=	sysutils
MASTER_SITES=	http://www.libimobiledevice.org/downloads/

MAINTAINER=	g.veniamin@googlemail.com
COMMENT=

GNU_CONFIGURE=	yes
USE_BZIP2=	yes
CONFIGURE_ENV=	CPPFLAGS="-I/usr/local/include" \
		LDFLAGS="-L/usr/local/lib"

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
