# New ports collection makefile for:	nmapsi4
# Date created:		2009-10-30
# Whom:			Gvozdikov Veniamin <g.veniamin@googlemail.com>
#
# $FreeBSD$
#

PORTNAME=	nmapsi4
PORTVERSION=	0.1.1
CATEGORIES=	security
MASTER_SITES=	GOOGLE_CODE
DISTNAME=	${PORTNAME}-${PORTVERSION}

MAINTAINER=	g.veniamin@googlemail.com
COMMENT=	GUI frontend for the nmap scanning utility

USE_CMAKE= 	yes
USE_QT_VER=	4
OMPONENTS=	gui xml qmake_build uic_build moc_build rcc_build

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
