# New ports collection makefile for:	erlyvideo
# Date created:		2010-07-29
# Whom:			Gvozdikov Veniamin <g.veniamin@googlemail.com>
#
# $FreeBSD$
#

PORTNAME=	erlyvideo
PORTVERSION=
CATEGORIES=	multimedia
MASTER_SITES=
#EXTRACT_ONLY=

MAINTAINER=	g.veniamin@googlemail.com
COMMENT=

BUILD_DEPENDS=	erlc:${PORTSDIR}/lang/erlang
RUN_DEPENDS=	erl:${PORTSDIR}/lang/erlang

USE_GMAKE=	yes

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
