# New ports collection makefile for:	linux-f10-libxslt
# Date created:		2009-11-10
# Whom:			Gvozdikov Veniamin <g.veniamin@googlemail.com>
#
# $FreeBSD$
#

PORTNAME=	libxslt
PORTVERSION=	1.1.24
CATEGORIES=	textproc
PKGNAMEPREFIX=	linux-f10-
DISTNAME=	${PORTNAME}-${PORTVERSION}-${RPMVERSION}

MAINTAINER=	g.veniamin@googlemail.com
COMMENT=	The XSLT C library for GNOME

ONLY_FOR_ARCHS=	i386 amd64
USE_LINUX_RPM=	yes
LINUX_DIST_VER=	10
USE_LDCONFIG=	yes
RPMVERSION=	2.fc10

.include <bsd.port.mk>
