# New ports collection makefile for:	activemq
# Date created:		2010-02-07
# Whom:			Gvozdikov Veniamin <g.veniamin@googlemail.com>
#
# $FreeBSD$
#

PORTNAME=	activemq
PORTVERSION=	5.3.0
#PORTREVISION=	0
#PORTEPOCH=	0
CATEGORIES=	www
MASTER_SITES=	http://www.sai.msu.su/apache/${PORTNAME}/apache-${PORTNAME}/${PORTVERSION}/ \
		ftp://apache.rinet.ru/pub/mirror/apache.org/dist/${PORTNAME}/apache-${PORTNAME}/${PORTVERSION}/ \
		http://www.apache.org/dist/${PORTNAME}/apache-${PORTNAME}/${PORTVERSION}/ \
		http://www.eu.apache.org/dist/${PORTNAME}/apache-${PORTNAME}/${PORTVERSION}/
#MASTER_SITE_SUBDIR=
#PKGNAMEPREFIX=
#PKGNAMESUFFIX=
DISTNAME=	apache-${PORTNAME}-${PORTVERSION}-bin
#EXTRACT_SUFX=
#DISTFILES=
#DIST_SUBDIR=	${PORTNAME}
#EXTRACT_ONLY=

MAINTAINER=	g.veniamin@googlemail.com
COMMENT=

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
