# New ports collection makefile for:	cursor-chameleon-white
# Date created:		2009-11-14
# Whom:			Gvozdikov Veniamin <g.veniamin@googlemail.com>
#
# $FreeBSD: ports/x11-themes/cursor-chameleon-white/Makefile,v 1.1 2010/08/03 09:45:10 makc Exp $
#

PORTNAME=	chameleon
PORTVERSION=	0.5
CATEGORIES=	x11-themes
MASTER_SITES=	http://www.egregorion.net/works/
PKGNAMEPREFIX=	cursor-
PKGNAMESUFFIX=	-white
DISTNAME=	Chameleon-White-${PORTVERSION}

MAINTAINER=	g.veniamin@googlemail.com
COMMENT=	Chameleon Xcursors theme

THEME=		White

.include "${.CURDIR}/../cursor-chameleon-white/files/Makefile.common"
.include <bsd.port.mk>
