# New ports collection makefile for:	cpassman
# Date created:		2010-06-10
# Whom:			Gvozdikov Veniamin <g.veniamin@googlemail.com>
#
# $FreeBSD$
#

PORTNAME=	cpassman
PORTVERSION=	1.52
CATEGORIES=	www
MASTER_SITES=	SF/communitypasswo/
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	g.veniamin@googlemail.com
COMMENT=	Collaborative Passwords Manager

USE_ZIP=	yes
USE_PHP=	mysql
WANT_PHP_WEB=	yes
NO_BUILD=	yes

.include <bsd.port.mk>
