# New ports collection makefile for:	rubygem-librmpd
# Date created:		2010-05-06
# Whom:			Gvozdikov Veniamin <g.veniamin@googlemail.com>
#
# $FreeBSD: ports/audio/rubygem-librmpd/Makefile,v 1.1 2010/05/16 09:15:38 miwi Exp $
#

PORTNAME=	librmpd
PORTVERSION=	0.1.1
CATEGORIES=	audio rubygems
MASTER_SITES=	RF

MAINTAINER=	g.veniamin@googlemail.com
COMMENT=	Is a simple yet powerful Music Player Daemon library

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

.include <bsd.port.mk>
