# New ports collection makefile for:	usbmuxd
# Date created:		2010-09-22
# Whom:			Gvozdikov Veniamin <g.veniamin@googlemail.com>
#
# $FreeBSD$
#

PORTNAME=	usbmuxd
PORTVERSION=	1.0.5
CATEGORIES=	sysutils
MASTER_SITES=	http://marcansoft.com/uploads/${PORTNAME}/

MAINTAINER=	g.veniamin@googlemail.com
COMMENT=	USB multiplexing daemon

USE_CMAKE=	yes
USE_BZIP2=	yes
USE_LDCONFIG=	yes

LICENSE=	GPLv3

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
