# New ports collection makefile for:	FCGI
# Date created:		2011-02-18
# Whom:			Gvozdikov Veniamin <g.veniamin@googlemail.com>
#
# $FreeBSD$
#

PORTNAME=	FCGI
PORTVERSION=	0.71
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	g.veniamin@googlemail.com
COMMENT=	FCGI - Fast CGI module

PERL_CONFIGURE=	yes

MAN3=		FCGI.3

.include <bsd.port.mk>
