# New ports collection makefile for:	stardict-pc
# Date created:		2010-03-16
# Whom:			Gvozdikov Veniamin <g.veniamin@googlemail.com>
#
# $FreeBSD: ports/russian/stardict-pc/Makefile,v 1.1 2010/03/24 19:35:33 makc Exp $
#

PORTNAME=	stardict-pc
PORTVERSION=	2.4.2
CATEGORIES=	russian
MASTER_SITES=	SF/stardict/stardict-dictionaries-ru/${PORTVERSION}
DISTNAME=	${PORTNAME}-user-ru-${PORTVERSION}

MAINTAINER=	g.veniamin@googlemail.com
COMMENT=	English-Russian PC-user dictionary

.include "${.CURDIR}/../stardict-mueller7/files/Makefile.common"
.include <bsd.port.mk>
