# New ports collection makefile for:	cairo-dock
# Date created:		2010-02-04
# Whom:			Gvozdikov Veniamin <g.veniamin@googlemail.com>
#
# $FreeBSD$
#

PORTNAME=	cairo-dock
PORTVERSION=	2.1.2
CATEGORIES=	x11
MASTER_SITES=	http://launchpadlibrarian.net/36753341/
DISTNAME=	${PORTNAME}-${PORTVERSION}-4

MAINTAINER=	g.veniamin@googlemail.com
COMMENT=	Is a light and eye-candy dock to launch your programs easily

USE_GMAKE=	yes
WRKSRC=		${WRKDIR}/${PORTNAME}-${PORTVERSION}-4

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
