# New ports collection makefile for:	linux-f10-ORBit2
# Date created:		2009-11-10
# Whom:			Gvozdikov Veniamin <g.veniamin@googlemail.com>
#
# $FreeBSD$
#

PORTNAME=	ORBit2
PORTVERSION=	2.14.16
CATEGORIES=	devel linux
PKGNAMEPREFIX=	linux-f10-
DISTNAME=	${PORTNAME}-${PORTVERSION}-${RPMVERSION}

MAINTAINER=	g.veniamin@googlemail.com
COMMENT=	High-performance CORBA ORB with support for the C languag

ONLY_FOR_ARCHS=	i386 amd64
USE_LINUX_RPM=	yes
LINUX_DIST_VER=	10
USE_LDCONFIG=	yes
RPMVERSION=	1.fc10

.include <bsd.port.mk>
